# mkdocs.yml
site_name: AFRH-IRIS Developer Documentation
theme:
  name: material
  features:
    - navigation.expand
markdown_extensions:
  - admonition
  - toc:
      toc_depth: 3
nav:
  - 'index.md'
  - 'project.md'
  - 'package.md'
  - 'map-layers.md'
  - 'management.md'
  - 'permissions.md'
