# Generated by Django 3.2.14 on 2022-10-03 14:44

from django.db import migrations

from arches.app.models.models import MapLayer


def modify_arches_defaults(apps, schema_editor):
    for ml in MapLayer.objects.all():
        if ml.name == "streets":
            ml.name = "Streets"
            ml.save()
        if ml.name == "satellite":
            ml.name = "Aerial Imagery"
            ml.save()

def undo(apps, schema_editor):
    for ml in MapLayer.objects.all():
        if ml.name == "Streets":
            ml.name = "streets"
            ml.save()
        if ml.name == "Aerial Imagery":
            ml.name = "satellite"
            ml.save()


class Migration(migrations.Migration):

    dependencies = [
        ("models", "__latest__"),
    ]

    operations = [
        migrations.RunPython(modify_arches_defaults, undo)
    ]
