# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 18:47
from __future__ import unicode_literals

from django.db import migrations
from django.core import management

from arches.app.models.models import MapLayer


def modify_arches_defaults(apps, schema_editor):

    for ml in MapLayer.objects.all():
        if ml.name == "streets":
            ml.name = "Streets"
            ml.save()
        if ml.name == "satellite":
            ml.name = "Aerial Imagery"
            ml.save()

def undo(apps, schema_editor):
    for ml in MapLayer.objects.all():
        if ml.name == "Streets":
            ml.name = "streets"
            ml.save()
        if ml.name == "Aerial Imagery":
            ml.name = "satellite"
            ml.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '5712_update_sys_setting'),
    ]

    operations = [
        migrations.RunPython(modify_arches_defaults, undo)
    ]
